### ISSUE TITLE
Unable to activate the plugin

### ISSUE THREAD

**Issue by Keyaku** [funabab/godot-git-control#2]
**System - Godot version**:
macOS Sierra 10.12.1 - Godot-master

**Problem**:
Your plugin contains at least one initialization error.

First one that comes up is in plugin.gd: `error(13, 156): invalid index 'GitManager' in constant expression`.

I'm not sure what you intend by creating a single class in a file, but you can just remove that line (leaving only `extends Object`) and then swapping the `GitManager.new`with just `new`.

In fact, you should do this with all the script files. I think I understand what you're doing, but you're just complicating the entire process.

**Comment by williamd1k0** [comment]
There is a problem to use the plugin in recent versions of godot, but the PR #1 should fix.

**Comment by iamfunsho** [comment]
Thanks @williamd1k0, i was totally unaware of that,  time to update the plugin on the asset library.
