### ISSUE TITLE
"Git not configured" fatal error

### ISSUE THREAD

**Issue by Keyaku** [funabab/godot-git-control#3]
So, I manage many repos on my machine, so *of course* I have Git set up with my e-mail and username.

And yet, upon activation, I get a "Git not configured" error from your plugin.

**UPDATE**:
It **must** failing to fetch my data from my system.

**Comment by iamfunsho** [comment]
Please what OS

**Comment by Keyaku** [comment]
Sorry about that.

Running macOs Sierra (10.12.1) and Godot from master.

**Comment by iamfunsho** [comment]
The problem is that i didn't test it on OSX cause i don't own a Mac or Hack but can you please run this command in your terminal and tell me what it prints

whereis -b git

**Comment by Keyaku** [comment]
I found the problem.

Just swap the line (at [command_manager.gd::76](https://github.com/funabab/godot-git-control/blob/master/addons/godot-git-control.funabab/scripts/command_manager.gd#L76)):
`return self.run_command(["-b", "git"], "whereis")[0].strip_edges();`
with
`return self.run_command(["git"], "whereis")[0].strip_edges();`

OS X does not support the `-b` flag in `whereis`.

Also, reminder: don't forget to update the plugin version number in [plugin.cfg::7](https://github.com/funabab/godot-git-control/blob/master/addons/godot-git-control.funabab/plugin.cfg#L7)! You forgot the last time

**Comment by iamfunsho** [comment]
What a coincidence :D, I have already change from using whereis to which binary (for searching for git) on both linux and mac (I have already pushed the changes). Please test it to see if there are any issues.

**Comment by iamfunsho** [comment]
You are free to close this issue if everything works fine. Also since it's still in alpha (and there are still some stuffs i will love to add) , i don't really what to change the version, i only did that because of asset-library. Maybe when i push a stable version (hopefully this weekend), i will update it.

**Comment by Keyaku** [comment]
I would, but this wasn't yet updated on the AssetLib D:

No matter, I downloaded the changed files and applied them. Works great! Thanks.
