### ISSUE TITLE
Push

### ISSUE THREAD

**Issue by testman42** [funabab/godot-git-control#5]
> Push: This was not added due to some known issues but i may consider adding them in the future if i find a workaround

What known issues?
What do you have to work around to get it working?
What can I do to help?

I think that having push would be very very useful.

**Comment by iamfunsho** [comment]
Most issues are mainly due to credentials management but there are plans to add it and other features before a stable version (v1.0). I have been busy with other stuff but it still in development

**Comment by iamfunsho** [comment]
All remote features have currently been removed until a better way of managing user credentials has being thought out
