### ISSUE TITLE
Suggestion: Init local repo

### ISSUE THREAD

**Issue by Warlaan** [funabab/godot-git-control#6]
Hi, I just submitted a similar plugin for Mercurial, so I checked out your Git plugin to see how you went at it.
Let's say you put a lot more work into your plugin than I did, since I just open the appropriate windows from the Tortoise-tool (in my case TortoiseHg). 

In any case there's one thing where my plugin works differently from yours: when you install my plugin it doesn't expect you to have the project folder under version control. Instead you can click a button to turn the project folder into a local repo (it just runs "hg init" resp. "git init").
For many small test projects I don't need an online repository, and why create a repo folder first to put the project in when that can just as easily be done by the plugin?

**Comment by iamfunsho** [comment]
thanks for the suggestion, this is now added in current version
