### ISSUE TITLE
whats the best way to install the plugin §

### ISSUE THREAD

**Issue by toger5** [funabab/godot-git-control#7]
sorry this might be a little unrelated to your plugin...
When I install it for each individual project it gets a little annoying since I need to install all the time.
and since this plugin doesn't has any functionality which has to be present so my game also works on other machines I wanted to know if I can install it for the editor?

or what is you approach in using it?

**Comment by iamfunsho** [comment]
this is not specific to the plugin cause it's basically how the assetlib works.. not much i can do

**Comment by toger5** [comment]
I created a issue in the godot repo that a system wide plugin directory would be desirable
